CREATE SCHEMA IF NOT EXISTS tech_task_db;

CREATE TABLE IF NOT EXISTS users (
	id VARCHAR(255) NOT NULL PRIMARY KEY,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS files (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL, -- это filekey
    ext VARCHAR(255) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    content_size VARCHAR(255) NOT NULL,
    upload_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    user_id VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
